backend:
  name: git-gateway
  branch: events # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "Events" # Used in routes, e.g., /admin/collections/blog
    label: "Event" # Used in the UI
    folder: "events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start Date(hidden, just for page order)", name: "start_date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}